import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import {
  IsEnum,
  IsNumber,
  IsOptional,
  Max,
  Min,
  ValidationOptions,
} from 'class-validator';

interface NumberApiPropertyOptions {
  min?: number;
  max?: number;
  optional?: boolean;
  readOnly?: boolean; // E.g. for IDs which are generated by the DB
  enum?: object;
  description?: string;
  example?: number;
  nullable?: boolean;
  validationOptions?: ValidationOptions;
}

export function NumberApiProperty(options?: NumberApiPropertyOptions) {
  const decorators: PropertyDecorator[] = [];

  if (!options?.readOnly) {
    decorators.push(IsNumber({}, options?.validationOptions));
  }

  if (options?.readOnly || options?.optional) {
    decorators.push(IsOptional());
  }

  if (options?.min !== undefined) {
    decorators.push(Min(options.min, options?.validationOptions));
  }

  if (options?.max !== undefined) {
    decorators.push(Max(options.max, options?.validationOptions));
  }

  if (options?.enum) {
    decorators.push(IsEnum(options.enum, options?.validationOptions));
  }

  decorators.push(
    ApiProperty({
      type: Number,
      example: options?.example,
      description: options?.description,
      nullable: options?.nullable === true,
      required: !options?.readOnly && options?.optional !== true,
      readOnly: options?.readOnly,
    }),
  );

  return applyDecorators(...decorators);
}
