

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."action" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" bigint,
    "level" bigint,
    "name" "text" DEFAULT ''::"text",
    "description" "text" DEFAULT ''::"text"
);


ALTER TABLE "public"."action" OWNER TO "postgres";


ALTER TABLE "public"."action" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."action_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."habit" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "completed_at" timestamp with time zone DEFAULT "now"(),
    "note" "text" DEFAULT ''::"text",
    "action_id" bigint NOT NULL
);


ALTER TABLE "public"."habit" OWNER TO "postgres";


COMMENT ON TABLE "public"."habit" IS 'A way of acting fixed through repetition';



ALTER TABLE "public"."habit" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."habit_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."action"
    ADD CONSTRAINT "action_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."action"
    ADD CONSTRAINT "action_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."habit"
    ADD CONSTRAINT "habit_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."habit"
    ADD CONSTRAINT "habit_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."habit"
    ADD CONSTRAINT "habit_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "public"."action"("id");



ALTER TABLE "public"."action" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."habit" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON TABLE "public"."action" TO "anon";
GRANT ALL ON TABLE "public"."action" TO "authenticated";
GRANT ALL ON TABLE "public"."action" TO "service_role";



GRANT ALL ON SEQUENCE "public"."action_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."action_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."action_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."habit" TO "anon";
GRANT ALL ON TABLE "public"."habit" TO "authenticated";
GRANT ALL ON TABLE "public"."habit" TO "service_role";



GRANT ALL ON SEQUENCE "public"."habit_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."habit_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."habit_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























drop extension if exists "pg_net";


